[project]
name = "minecraft-server-manager"
version = "1.6"
description = "Minecraft 伺服器管理器"
readme = "README.md"
requires-python = ">=3.9, <3.13"
license = { file = "LICENSE" }

dependencies = [
  "requests>=2.32.5",
  "urllib3>=2.6.2",
  "aiohttp>=3.13.2",
  "psutil>=7.1.3",
  "packaging>=25.0",
  "rich>=14.2.0",
  "lxml>=6.0.2",
  "toml>=0.10.2",
  "customtkinter>=5.2.2",
  "nuitka>=2.8.9",
  "zstandard>=0.15",
  "uv>=0.6.0",
  "loguru>=0.7.3",
]

[project.scripts]
minecraft-server-manager = "src.main:main"

[tool.uv]
managed = true
